// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/proto/payment.proto

package payment.model;

public final class PaymentOuterClass {
  private PaymentOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PaymentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Payment)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string paymentID = 1;</code>
     * @return Whether the paymentID field is set.
     */
    boolean hasPaymentID();
    /**
     * <code>required string paymentID = 1;</code>
     * @return The paymentID.
     */
    java.lang.String getPaymentID();
    /**
     * <code>required string paymentID = 1;</code>
     * @return The bytes for paymentID.
     */
    com.google.protobuf.ByteString
        getPaymentIDBytes();

    /**
     * <code>required string tenantID = 2;</code>
     * @return Whether the tenantID field is set.
     */
    boolean hasTenantID();
    /**
     * <code>required string tenantID = 2;</code>
     * @return The tenantID.
     */
    java.lang.String getTenantID();
    /**
     * <code>required string tenantID = 2;</code>
     * @return The bytes for tenantID.
     */
    com.google.protobuf.ByteString
        getTenantIDBytes();

    /**
     * <code>required .google.protobuf.Timestamp txnDate = 3;</code>
     * @return Whether the txnDate field is set.
     */
    boolean hasTxnDate();
    /**
     * <code>required .google.protobuf.Timestamp txnDate = 3;</code>
     * @return The txnDate.
     */
    com.google.protobuf.Timestamp getTxnDate();
    /**
     * <code>required .google.protobuf.Timestamp txnDate = 3;</code>
     */
    com.google.protobuf.TimestampOrBuilder getTxnDateOrBuilder();

    /**
     * <code>required string currentStage = 4;</code>
     * @return Whether the currentStage field is set.
     */
    boolean hasCurrentStage();
    /**
     * <code>required string currentStage = 4;</code>
     * @return The currentStage.
     */
    java.lang.String getCurrentStage();
    /**
     * <code>required string currentStage = 4;</code>
     * @return The bytes for currentStage.
     */
    com.google.protobuf.ByteString
        getCurrentStageBytes();
  }
  /**
   * Protobuf type {@code Payment}
   */
  public static final class Payment extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Payment)
      PaymentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Payment.newBuilder() to construct.
    private Payment(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Payment() {
      paymentID_ = "";
      tenantID_ = "";
      currentStage_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Payment();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Payment(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              paymentID_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              tenantID_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) != 0)) {
                subBuilder = txnDate_.toBuilder();
              }
              txnDate_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(txnDate_);
                txnDate_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              currentStage_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return payment.model.PaymentOuterClass.internal_static_Payment_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return payment.model.PaymentOuterClass.internal_static_Payment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              payment.model.PaymentOuterClass.Payment.class, payment.model.PaymentOuterClass.Payment.Builder.class);
    }

    private int bitField0_;
    public static final int PAYMENTID_FIELD_NUMBER = 1;
    private volatile java.lang.Object paymentID_;
    /**
     * <code>required string paymentID = 1;</code>
     * @return Whether the paymentID field is set.
     */
    @java.lang.Override
    public boolean hasPaymentID() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string paymentID = 1;</code>
     * @return The paymentID.
     */
    @java.lang.Override
    public java.lang.String getPaymentID() {
      java.lang.Object ref = paymentID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          paymentID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string paymentID = 1;</code>
     * @return The bytes for paymentID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPaymentIDBytes() {
      java.lang.Object ref = paymentID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        paymentID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TENANTID_FIELD_NUMBER = 2;
    private volatile java.lang.Object tenantID_;
    /**
     * <code>required string tenantID = 2;</code>
     * @return Whether the tenantID field is set.
     */
    @java.lang.Override
    public boolean hasTenantID() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string tenantID = 2;</code>
     * @return The tenantID.
     */
    @java.lang.Override
    public java.lang.String getTenantID() {
      java.lang.Object ref = tenantID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tenantID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string tenantID = 2;</code>
     * @return The bytes for tenantID.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTenantIDBytes() {
      java.lang.Object ref = tenantID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tenantID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TXNDATE_FIELD_NUMBER = 3;
    private com.google.protobuf.Timestamp txnDate_;
    /**
     * <code>required .google.protobuf.Timestamp txnDate = 3;</code>
     * @return Whether the txnDate field is set.
     */
    @java.lang.Override
    public boolean hasTxnDate() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required .google.protobuf.Timestamp txnDate = 3;</code>
     * @return The txnDate.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getTxnDate() {
      return txnDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : txnDate_;
    }
    /**
     * <code>required .google.protobuf.Timestamp txnDate = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getTxnDateOrBuilder() {
      return txnDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : txnDate_;
    }

    public static final int CURRENTSTAGE_FIELD_NUMBER = 4;
    private volatile java.lang.Object currentStage_;
    /**
     * <code>required string currentStage = 4;</code>
     * @return Whether the currentStage field is set.
     */
    @java.lang.Override
    public boolean hasCurrentStage() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required string currentStage = 4;</code>
     * @return The currentStage.
     */
    @java.lang.Override
    public java.lang.String getCurrentStage() {
      java.lang.Object ref = currentStage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          currentStage_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string currentStage = 4;</code>
     * @return The bytes for currentStage.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCurrentStageBytes() {
      java.lang.Object ref = currentStage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currentStage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPaymentID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTenantID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTxnDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCurrentStage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, paymentID_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tenantID_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeMessage(3, getTxnDate());
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, currentStage_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, paymentID_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tenantID_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getTxnDate());
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, currentStage_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof payment.model.PaymentOuterClass.Payment)) {
        return super.equals(obj);
      }
      payment.model.PaymentOuterClass.Payment other = (payment.model.PaymentOuterClass.Payment) obj;

      if (hasPaymentID() != other.hasPaymentID()) return false;
      if (hasPaymentID()) {
        if (!getPaymentID()
            .equals(other.getPaymentID())) return false;
      }
      if (hasTenantID() != other.hasTenantID()) return false;
      if (hasTenantID()) {
        if (!getTenantID()
            .equals(other.getTenantID())) return false;
      }
      if (hasTxnDate() != other.hasTxnDate()) return false;
      if (hasTxnDate()) {
        if (!getTxnDate()
            .equals(other.getTxnDate())) return false;
      }
      if (hasCurrentStage() != other.hasCurrentStage()) return false;
      if (hasCurrentStage()) {
        if (!getCurrentStage()
            .equals(other.getCurrentStage())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPaymentID()) {
        hash = (37 * hash) + PAYMENTID_FIELD_NUMBER;
        hash = (53 * hash) + getPaymentID().hashCode();
      }
      if (hasTenantID()) {
        hash = (37 * hash) + TENANTID_FIELD_NUMBER;
        hash = (53 * hash) + getTenantID().hashCode();
      }
      if (hasTxnDate()) {
        hash = (37 * hash) + TXNDATE_FIELD_NUMBER;
        hash = (53 * hash) + getTxnDate().hashCode();
      }
      if (hasCurrentStage()) {
        hash = (37 * hash) + CURRENTSTAGE_FIELD_NUMBER;
        hash = (53 * hash) + getCurrentStage().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static payment.model.PaymentOuterClass.Payment parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static payment.model.PaymentOuterClass.Payment parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static payment.model.PaymentOuterClass.Payment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static payment.model.PaymentOuterClass.Payment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static payment.model.PaymentOuterClass.Payment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static payment.model.PaymentOuterClass.Payment parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static payment.model.PaymentOuterClass.Payment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static payment.model.PaymentOuterClass.Payment parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static payment.model.PaymentOuterClass.Payment parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static payment.model.PaymentOuterClass.Payment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static payment.model.PaymentOuterClass.Payment parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static payment.model.PaymentOuterClass.Payment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(payment.model.PaymentOuterClass.Payment prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Payment}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Payment)
        payment.model.PaymentOuterClass.PaymentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return payment.model.PaymentOuterClass.internal_static_Payment_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return payment.model.PaymentOuterClass.internal_static_Payment_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                payment.model.PaymentOuterClass.Payment.class, payment.model.PaymentOuterClass.Payment.Builder.class);
      }

      // Construct using payment.model.PaymentOuterClass.Payment.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTxnDateFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        paymentID_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        tenantID_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (txnDateBuilder_ == null) {
          txnDate_ = null;
        } else {
          txnDateBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        currentStage_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return payment.model.PaymentOuterClass.internal_static_Payment_descriptor;
      }

      @java.lang.Override
      public payment.model.PaymentOuterClass.Payment getDefaultInstanceForType() {
        return payment.model.PaymentOuterClass.Payment.getDefaultInstance();
      }

      @java.lang.Override
      public payment.model.PaymentOuterClass.Payment build() {
        payment.model.PaymentOuterClass.Payment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public payment.model.PaymentOuterClass.Payment buildPartial() {
        payment.model.PaymentOuterClass.Payment result = new payment.model.PaymentOuterClass.Payment(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.paymentID_ = paymentID_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.tenantID_ = tenantID_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          if (txnDateBuilder_ == null) {
            result.txnDate_ = txnDate_;
          } else {
            result.txnDate_ = txnDateBuilder_.build();
          }
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.currentStage_ = currentStage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof payment.model.PaymentOuterClass.Payment) {
          return mergeFrom((payment.model.PaymentOuterClass.Payment)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(payment.model.PaymentOuterClass.Payment other) {
        if (other == payment.model.PaymentOuterClass.Payment.getDefaultInstance()) return this;
        if (other.hasPaymentID()) {
          bitField0_ |= 0x00000001;
          paymentID_ = other.paymentID_;
          onChanged();
        }
        if (other.hasTenantID()) {
          bitField0_ |= 0x00000002;
          tenantID_ = other.tenantID_;
          onChanged();
        }
        if (other.hasTxnDate()) {
          mergeTxnDate(other.getTxnDate());
        }
        if (other.hasCurrentStage()) {
          bitField0_ |= 0x00000008;
          currentStage_ = other.currentStage_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasPaymentID()) {
          return false;
        }
        if (!hasTenantID()) {
          return false;
        }
        if (!hasTxnDate()) {
          return false;
        }
        if (!hasCurrentStage()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        payment.model.PaymentOuterClass.Payment parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (payment.model.PaymentOuterClass.Payment) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object paymentID_ = "";
      /**
       * <code>required string paymentID = 1;</code>
       * @return Whether the paymentID field is set.
       */
      public boolean hasPaymentID() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string paymentID = 1;</code>
       * @return The paymentID.
       */
      public java.lang.String getPaymentID() {
        java.lang.Object ref = paymentID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            paymentID_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string paymentID = 1;</code>
       * @return The bytes for paymentID.
       */
      public com.google.protobuf.ByteString
          getPaymentIDBytes() {
        java.lang.Object ref = paymentID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          paymentID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string paymentID = 1;</code>
       * @param value The paymentID to set.
       * @return This builder for chaining.
       */
      public Builder setPaymentID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        paymentID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string paymentID = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPaymentID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        paymentID_ = getDefaultInstance().getPaymentID();
        onChanged();
        return this;
      }
      /**
       * <code>required string paymentID = 1;</code>
       * @param value The bytes for paymentID to set.
       * @return This builder for chaining.
       */
      public Builder setPaymentIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        paymentID_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object tenantID_ = "";
      /**
       * <code>required string tenantID = 2;</code>
       * @return Whether the tenantID field is set.
       */
      public boolean hasTenantID() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string tenantID = 2;</code>
       * @return The tenantID.
       */
      public java.lang.String getTenantID() {
        java.lang.Object ref = tenantID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            tenantID_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string tenantID = 2;</code>
       * @return The bytes for tenantID.
       */
      public com.google.protobuf.ByteString
          getTenantIDBytes() {
        java.lang.Object ref = tenantID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tenantID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string tenantID = 2;</code>
       * @param value The tenantID to set.
       * @return This builder for chaining.
       */
      public Builder setTenantID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        tenantID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string tenantID = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTenantID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        tenantID_ = getDefaultInstance().getTenantID();
        onChanged();
        return this;
      }
      /**
       * <code>required string tenantID = 2;</code>
       * @param value The bytes for tenantID to set.
       * @return This builder for chaining.
       */
      public Builder setTenantIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        tenantID_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp txnDate_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> txnDateBuilder_;
      /**
       * <code>required .google.protobuf.Timestamp txnDate = 3;</code>
       * @return Whether the txnDate field is set.
       */
      public boolean hasTxnDate() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required .google.protobuf.Timestamp txnDate = 3;</code>
       * @return The txnDate.
       */
      public com.google.protobuf.Timestamp getTxnDate() {
        if (txnDateBuilder_ == null) {
          return txnDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : txnDate_;
        } else {
          return txnDateBuilder_.getMessage();
        }
      }
      /**
       * <code>required .google.protobuf.Timestamp txnDate = 3;</code>
       */
      public Builder setTxnDate(com.google.protobuf.Timestamp value) {
        if (txnDateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          txnDate_ = value;
          onChanged();
        } else {
          txnDateBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .google.protobuf.Timestamp txnDate = 3;</code>
       */
      public Builder setTxnDate(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (txnDateBuilder_ == null) {
          txnDate_ = builderForValue.build();
          onChanged();
        } else {
          txnDateBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .google.protobuf.Timestamp txnDate = 3;</code>
       */
      public Builder mergeTxnDate(com.google.protobuf.Timestamp value) {
        if (txnDateBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
              txnDate_ != null &&
              txnDate_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            txnDate_ =
              com.google.protobuf.Timestamp.newBuilder(txnDate_).mergeFrom(value).buildPartial();
          } else {
            txnDate_ = value;
          }
          onChanged();
        } else {
          txnDateBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .google.protobuf.Timestamp txnDate = 3;</code>
       */
      public Builder clearTxnDate() {
        if (txnDateBuilder_ == null) {
          txnDate_ = null;
          onChanged();
        } else {
          txnDateBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>required .google.protobuf.Timestamp txnDate = 3;</code>
       */
      public com.google.protobuf.Timestamp.Builder getTxnDateBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getTxnDateFieldBuilder().getBuilder();
      }
      /**
       * <code>required .google.protobuf.Timestamp txnDate = 3;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getTxnDateOrBuilder() {
        if (txnDateBuilder_ != null) {
          return txnDateBuilder_.getMessageOrBuilder();
        } else {
          return txnDate_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : txnDate_;
        }
      }
      /**
       * <code>required .google.protobuf.Timestamp txnDate = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getTxnDateFieldBuilder() {
        if (txnDateBuilder_ == null) {
          txnDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getTxnDate(),
                  getParentForChildren(),
                  isClean());
          txnDate_ = null;
        }
        return txnDateBuilder_;
      }

      private java.lang.Object currentStage_ = "";
      /**
       * <code>required string currentStage = 4;</code>
       * @return Whether the currentStage field is set.
       */
      public boolean hasCurrentStage() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required string currentStage = 4;</code>
       * @return The currentStage.
       */
      public java.lang.String getCurrentStage() {
        java.lang.Object ref = currentStage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            currentStage_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string currentStage = 4;</code>
       * @return The bytes for currentStage.
       */
      public com.google.protobuf.ByteString
          getCurrentStageBytes() {
        java.lang.Object ref = currentStage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currentStage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string currentStage = 4;</code>
       * @param value The currentStage to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentStage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        currentStage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string currentStage = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrentStage() {
        bitField0_ = (bitField0_ & ~0x00000008);
        currentStage_ = getDefaultInstance().getCurrentStage();
        onChanged();
        return this;
      }
      /**
       * <code>required string currentStage = 4;</code>
       * @param value The bytes for currentStage to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentStageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        currentStage_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Payment)
    }

    // @@protoc_insertion_point(class_scope:Payment)
    private static final payment.model.PaymentOuterClass.Payment DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new payment.model.PaymentOuterClass.Payment();
    }

    public static payment.model.PaymentOuterClass.Payment getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Payment>
        PARSER = new com.google.protobuf.AbstractParser<Payment>() {
      @java.lang.Override
      public Payment parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Payment(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Payment> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Payment> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public payment.model.PaymentOuterClass.Payment getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Payment_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Payment_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030main/proto/payment.proto\032\037google/proto" +
      "buf/timestamp.proto\"q\n\007Payment\022\021\n\tpaymen" +
      "tID\030\001 \002(\t\022\020\n\010tenantID\030\002 \002(\t\022+\n\007txnDate\030\003" +
      " \002(\0132\032.google.protobuf.Timestamp\022\024\n\014curr" +
      "entStage\030\004 \002(\tB\017\n\rpayment.model"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_Payment_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Payment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Payment_descriptor,
        new java.lang.String[] { "PaymentID", "TenantID", "TxnDate", "CurrentStage", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
