// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/proto/command.proto

package payment.framework.serializers;

public final class Command {
  private Command() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CommandProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CommandProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string currentStage = 1;</code>
     * @return Whether the currentStage field is set.
     */
    boolean hasCurrentStage();
    /**
     * <code>required string currentStage = 1;</code>
     * @return The currentStage.
     */
    java.lang.String getCurrentStage();
    /**
     * <code>required string currentStage = 1;</code>
     * @return The bytes for currentStage.
     */
    com.google.protobuf.ByteString
        getCurrentStageBytes();

    /**
     * <code>optional .CommandProto.PipelineStages processingPipeline = 2;</code>
     * @return Whether the processingPipeline field is set.
     */
    boolean hasProcessingPipeline();
    /**
     * <code>optional .CommandProto.PipelineStages processingPipeline = 2;</code>
     * @return The processingPipeline.
     */
    payment.framework.serializers.Command.CommandProto.PipelineStages getProcessingPipeline();
    /**
     * <code>optional .CommandProto.PipelineStages processingPipeline = 2;</code>
     */
    payment.framework.serializers.Command.CommandProto.PipelineStagesOrBuilder getProcessingPipelineOrBuilder();
  }
  /**
   * Protobuf type {@code CommandProto}
   */
  public static final class CommandProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CommandProto)
      CommandProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CommandProto.newBuilder() to construct.
    private CommandProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CommandProto() {
      currentStage_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CommandProto();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CommandProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              currentStage_ = bs;
              break;
            }
            case 18: {
              payment.framework.serializers.Command.CommandProto.PipelineStages.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) != 0)) {
                subBuilder = processingPipeline_.toBuilder();
              }
              processingPipeline_ = input.readMessage(payment.framework.serializers.Command.CommandProto.PipelineStages.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(processingPipeline_);
                processingPipeline_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return payment.framework.serializers.Command.internal_static_CommandProto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return payment.framework.serializers.Command.internal_static_CommandProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              payment.framework.serializers.Command.CommandProto.class, payment.framework.serializers.Command.CommandProto.Builder.class);
    }

    public interface StageOrBuilder extends
        // @@protoc_insertion_point(interface_extends:CommandProto.Stage)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string stage = 1;</code>
       * @return Whether the stage field is set.
       */
      boolean hasStage();
      /**
       * <code>required string stage = 1;</code>
       * @return The stage.
       */
      java.lang.String getStage();
      /**
       * <code>required string stage = 1;</code>
       * @return The bytes for stage.
       */
      com.google.protobuf.ByteString
          getStageBytes();

      /**
       * <code>required bool status = 2;</code>
       * @return Whether the status field is set.
       */
      boolean hasStatus();
      /**
       * <code>required bool status = 2;</code>
       * @return The status.
       */
      boolean getStatus();
    }
    /**
     * Protobuf type {@code CommandProto.Stage}
     */
    public static final class Stage extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:CommandProto.Stage)
        StageOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Stage.newBuilder() to construct.
      private Stage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Stage() {
        stage_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Stage();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Stage(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                stage_ = bs;
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                status_ = input.readBool();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return payment.framework.serializers.Command.internal_static_CommandProto_Stage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return payment.framework.serializers.Command.internal_static_CommandProto_Stage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                payment.framework.serializers.Command.CommandProto.Stage.class, payment.framework.serializers.Command.CommandProto.Stage.Builder.class);
      }

      private int bitField0_;
      public static final int STAGE_FIELD_NUMBER = 1;
      private volatile java.lang.Object stage_;
      /**
       * <code>required string stage = 1;</code>
       * @return Whether the stage field is set.
       */
      @java.lang.Override
      public boolean hasStage() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string stage = 1;</code>
       * @return The stage.
       */
      @java.lang.Override
      public java.lang.String getStage() {
        java.lang.Object ref = stage_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            stage_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string stage = 1;</code>
       * @return The bytes for stage.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getStageBytes() {
        java.lang.Object ref = stage_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          stage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int STATUS_FIELD_NUMBER = 2;
      private boolean status_;
      /**
       * <code>required bool status = 2;</code>
       * @return Whether the status field is set.
       */
      @java.lang.Override
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required bool status = 2;</code>
       * @return The status.
       */
      @java.lang.Override
      public boolean getStatus() {
        return status_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasStage()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasStatus()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, stage_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          output.writeBool(2, status_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, stage_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(2, status_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof payment.framework.serializers.Command.CommandProto.Stage)) {
          return super.equals(obj);
        }
        payment.framework.serializers.Command.CommandProto.Stage other = (payment.framework.serializers.Command.CommandProto.Stage) obj;

        if (hasStage() != other.hasStage()) return false;
        if (hasStage()) {
          if (!getStage()
              .equals(other.getStage())) return false;
        }
        if (hasStatus() != other.hasStatus()) return false;
        if (hasStatus()) {
          if (getStatus()
              != other.getStatus()) return false;
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasStage()) {
          hash = (37 * hash) + STAGE_FIELD_NUMBER;
          hash = (53 * hash) + getStage().hashCode();
        }
        if (hasStatus()) {
          hash = (37 * hash) + STATUS_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
              getStatus());
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static payment.framework.serializers.Command.CommandProto.Stage parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static payment.framework.serializers.Command.CommandProto.Stage parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static payment.framework.serializers.Command.CommandProto.Stage parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static payment.framework.serializers.Command.CommandProto.Stage parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static payment.framework.serializers.Command.CommandProto.Stage parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static payment.framework.serializers.Command.CommandProto.Stage parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static payment.framework.serializers.Command.CommandProto.Stage parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static payment.framework.serializers.Command.CommandProto.Stage parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static payment.framework.serializers.Command.CommandProto.Stage parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static payment.framework.serializers.Command.CommandProto.Stage parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static payment.framework.serializers.Command.CommandProto.Stage parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static payment.framework.serializers.Command.CommandProto.Stage parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(payment.framework.serializers.Command.CommandProto.Stage prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code CommandProto.Stage}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:CommandProto.Stage)
          payment.framework.serializers.Command.CommandProto.StageOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return payment.framework.serializers.Command.internal_static_CommandProto_Stage_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return payment.framework.serializers.Command.internal_static_CommandProto_Stage_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  payment.framework.serializers.Command.CommandProto.Stage.class, payment.framework.serializers.Command.CommandProto.Stage.Builder.class);
        }

        // Construct using payment.framework.serializers.Command.CommandProto.Stage.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          stage_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          status_ = false;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return payment.framework.serializers.Command.internal_static_CommandProto_Stage_descriptor;
        }

        @java.lang.Override
        public payment.framework.serializers.Command.CommandProto.Stage getDefaultInstanceForType() {
          return payment.framework.serializers.Command.CommandProto.Stage.getDefaultInstance();
        }

        @java.lang.Override
        public payment.framework.serializers.Command.CommandProto.Stage build() {
          payment.framework.serializers.Command.CommandProto.Stage result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public payment.framework.serializers.Command.CommandProto.Stage buildPartial() {
          payment.framework.serializers.Command.CommandProto.Stage result = new payment.framework.serializers.Command.CommandProto.Stage(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            to_bitField0_ |= 0x00000001;
          }
          result.stage_ = stage_;
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.status_ = status_;
            to_bitField0_ |= 0x00000002;
          }
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof payment.framework.serializers.Command.CommandProto.Stage) {
            return mergeFrom((payment.framework.serializers.Command.CommandProto.Stage)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(payment.framework.serializers.Command.CommandProto.Stage other) {
          if (other == payment.framework.serializers.Command.CommandProto.Stage.getDefaultInstance()) return this;
          if (other.hasStage()) {
            bitField0_ |= 0x00000001;
            stage_ = other.stage_;
            onChanged();
          }
          if (other.hasStatus()) {
            setStatus(other.getStatus());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          if (!hasStage()) {
            return false;
          }
          if (!hasStatus()) {
            return false;
          }
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          payment.framework.serializers.Command.CommandProto.Stage parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (payment.framework.serializers.Command.CommandProto.Stage) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object stage_ = "";
        /**
         * <code>required string stage = 1;</code>
         * @return Whether the stage field is set.
         */
        public boolean hasStage() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>required string stage = 1;</code>
         * @return The stage.
         */
        public java.lang.String getStage() {
          java.lang.Object ref = stage_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              stage_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string stage = 1;</code>
         * @return The bytes for stage.
         */
        public com.google.protobuf.ByteString
            getStageBytes() {
          java.lang.Object ref = stage_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            stage_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string stage = 1;</code>
         * @param value The stage to set.
         * @return This builder for chaining.
         */
        public Builder setStage(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          stage_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string stage = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearStage() {
          bitField0_ = (bitField0_ & ~0x00000001);
          stage_ = getDefaultInstance().getStage();
          onChanged();
          return this;
        }
        /**
         * <code>required string stage = 1;</code>
         * @param value The bytes for stage to set.
         * @return This builder for chaining.
         */
        public Builder setStageBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          stage_ = value;
          onChanged();
          return this;
        }

        private boolean status_ ;
        /**
         * <code>required bool status = 2;</code>
         * @return Whether the status field is set.
         */
        @java.lang.Override
        public boolean hasStatus() {
          return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>required bool status = 2;</code>
         * @return The status.
         */
        @java.lang.Override
        public boolean getStatus() {
          return status_;
        }
        /**
         * <code>required bool status = 2;</code>
         * @param value The status to set.
         * @return This builder for chaining.
         */
        public Builder setStatus(boolean value) {
          bitField0_ |= 0x00000002;
          status_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bool status = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearStatus() {
          bitField0_ = (bitField0_ & ~0x00000002);
          status_ = false;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:CommandProto.Stage)
      }

      // @@protoc_insertion_point(class_scope:CommandProto.Stage)
      private static final payment.framework.serializers.Command.CommandProto.Stage DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new payment.framework.serializers.Command.CommandProto.Stage();
      }

      public static payment.framework.serializers.Command.CommandProto.Stage getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<Stage>
          PARSER = new com.google.protobuf.AbstractParser<Stage>() {
        @java.lang.Override
        public Stage parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Stage(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Stage> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Stage> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public payment.framework.serializers.Command.CommandProto.Stage getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public interface PipelineStagesOrBuilder extends
        // @@protoc_insertion_point(interface_extends:CommandProto.PipelineStages)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>repeated .CommandProto.Stage pipelineStage = 1;</code>
       */
      java.util.List<payment.framework.serializers.Command.CommandProto.Stage> 
          getPipelineStageList();
      /**
       * <code>repeated .CommandProto.Stage pipelineStage = 1;</code>
       */
      payment.framework.serializers.Command.CommandProto.Stage getPipelineStage(int index);
      /**
       * <code>repeated .CommandProto.Stage pipelineStage = 1;</code>
       */
      int getPipelineStageCount();
      /**
       * <code>repeated .CommandProto.Stage pipelineStage = 1;</code>
       */
      java.util.List<? extends payment.framework.serializers.Command.CommandProto.StageOrBuilder> 
          getPipelineStageOrBuilderList();
      /**
       * <code>repeated .CommandProto.Stage pipelineStage = 1;</code>
       */
      payment.framework.serializers.Command.CommandProto.StageOrBuilder getPipelineStageOrBuilder(
          int index);
    }
    /**
     * Protobuf type {@code CommandProto.PipelineStages}
     */
    public static final class PipelineStages extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:CommandProto.PipelineStages)
        PipelineStagesOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use PipelineStages.newBuilder() to construct.
      private PipelineStages(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private PipelineStages() {
        pipelineStage_ = java.util.Collections.emptyList();
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new PipelineStages();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private PipelineStages(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                  pipelineStage_ = new java.util.ArrayList<payment.framework.serializers.Command.CommandProto.Stage>();
                  mutable_bitField0_ |= 0x00000001;
                }
                pipelineStage_.add(
                    input.readMessage(payment.framework.serializers.Command.CommandProto.Stage.PARSER, extensionRegistry));
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000001) != 0)) {
            pipelineStage_ = java.util.Collections.unmodifiableList(pipelineStage_);
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return payment.framework.serializers.Command.internal_static_CommandProto_PipelineStages_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return payment.framework.serializers.Command.internal_static_CommandProto_PipelineStages_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                payment.framework.serializers.Command.CommandProto.PipelineStages.class, payment.framework.serializers.Command.CommandProto.PipelineStages.Builder.class);
      }

      public static final int PIPELINESTAGE_FIELD_NUMBER = 1;
      private java.util.List<payment.framework.serializers.Command.CommandProto.Stage> pipelineStage_;
      /**
       * <code>repeated .CommandProto.Stage pipelineStage = 1;</code>
       */
      @java.lang.Override
      public java.util.List<payment.framework.serializers.Command.CommandProto.Stage> getPipelineStageList() {
        return pipelineStage_;
      }
      /**
       * <code>repeated .CommandProto.Stage pipelineStage = 1;</code>
       */
      @java.lang.Override
      public java.util.List<? extends payment.framework.serializers.Command.CommandProto.StageOrBuilder> 
          getPipelineStageOrBuilderList() {
        return pipelineStage_;
      }
      /**
       * <code>repeated .CommandProto.Stage pipelineStage = 1;</code>
       */
      @java.lang.Override
      public int getPipelineStageCount() {
        return pipelineStage_.size();
      }
      /**
       * <code>repeated .CommandProto.Stage pipelineStage = 1;</code>
       */
      @java.lang.Override
      public payment.framework.serializers.Command.CommandProto.Stage getPipelineStage(int index) {
        return pipelineStage_.get(index);
      }
      /**
       * <code>repeated .CommandProto.Stage pipelineStage = 1;</code>
       */
      @java.lang.Override
      public payment.framework.serializers.Command.CommandProto.StageOrBuilder getPipelineStageOrBuilder(
          int index) {
        return pipelineStage_.get(index);
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        for (int i = 0; i < getPipelineStageCount(); i++) {
          if (!getPipelineStage(i).isInitialized()) {
            memoizedIsInitialized = 0;
            return false;
          }
        }
        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        for (int i = 0; i < pipelineStage_.size(); i++) {
          output.writeMessage(1, pipelineStage_.get(i));
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        for (int i = 0; i < pipelineStage_.size(); i++) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, pipelineStage_.get(i));
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof payment.framework.serializers.Command.CommandProto.PipelineStages)) {
          return super.equals(obj);
        }
        payment.framework.serializers.Command.CommandProto.PipelineStages other = (payment.framework.serializers.Command.CommandProto.PipelineStages) obj;

        if (!getPipelineStageList()
            .equals(other.getPipelineStageList())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (getPipelineStageCount() > 0) {
          hash = (37 * hash) + PIPELINESTAGE_FIELD_NUMBER;
          hash = (53 * hash) + getPipelineStageList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static payment.framework.serializers.Command.CommandProto.PipelineStages parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static payment.framework.serializers.Command.CommandProto.PipelineStages parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static payment.framework.serializers.Command.CommandProto.PipelineStages parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static payment.framework.serializers.Command.CommandProto.PipelineStages parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static payment.framework.serializers.Command.CommandProto.PipelineStages parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static payment.framework.serializers.Command.CommandProto.PipelineStages parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static payment.framework.serializers.Command.CommandProto.PipelineStages parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static payment.framework.serializers.Command.CommandProto.PipelineStages parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static payment.framework.serializers.Command.CommandProto.PipelineStages parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static payment.framework.serializers.Command.CommandProto.PipelineStages parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static payment.framework.serializers.Command.CommandProto.PipelineStages parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static payment.framework.serializers.Command.CommandProto.PipelineStages parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(payment.framework.serializers.Command.CommandProto.PipelineStages prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code CommandProto.PipelineStages}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:CommandProto.PipelineStages)
          payment.framework.serializers.Command.CommandProto.PipelineStagesOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return payment.framework.serializers.Command.internal_static_CommandProto_PipelineStages_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return payment.framework.serializers.Command.internal_static_CommandProto_PipelineStages_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  payment.framework.serializers.Command.CommandProto.PipelineStages.class, payment.framework.serializers.Command.CommandProto.PipelineStages.Builder.class);
        }

        // Construct using payment.framework.serializers.Command.CommandProto.PipelineStages.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
            getPipelineStageFieldBuilder();
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          if (pipelineStageBuilder_ == null) {
            pipelineStage_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            pipelineStageBuilder_.clear();
          }
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return payment.framework.serializers.Command.internal_static_CommandProto_PipelineStages_descriptor;
        }

        @java.lang.Override
        public payment.framework.serializers.Command.CommandProto.PipelineStages getDefaultInstanceForType() {
          return payment.framework.serializers.Command.CommandProto.PipelineStages.getDefaultInstance();
        }

        @java.lang.Override
        public payment.framework.serializers.Command.CommandProto.PipelineStages build() {
          payment.framework.serializers.Command.CommandProto.PipelineStages result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public payment.framework.serializers.Command.CommandProto.PipelineStages buildPartial() {
          payment.framework.serializers.Command.CommandProto.PipelineStages result = new payment.framework.serializers.Command.CommandProto.PipelineStages(this);
          int from_bitField0_ = bitField0_;
          if (pipelineStageBuilder_ == null) {
            if (((bitField0_ & 0x00000001) != 0)) {
              pipelineStage_ = java.util.Collections.unmodifiableList(pipelineStage_);
              bitField0_ = (bitField0_ & ~0x00000001);
            }
            result.pipelineStage_ = pipelineStage_;
          } else {
            result.pipelineStage_ = pipelineStageBuilder_.build();
          }
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof payment.framework.serializers.Command.CommandProto.PipelineStages) {
            return mergeFrom((payment.framework.serializers.Command.CommandProto.PipelineStages)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(payment.framework.serializers.Command.CommandProto.PipelineStages other) {
          if (other == payment.framework.serializers.Command.CommandProto.PipelineStages.getDefaultInstance()) return this;
          if (pipelineStageBuilder_ == null) {
            if (!other.pipelineStage_.isEmpty()) {
              if (pipelineStage_.isEmpty()) {
                pipelineStage_ = other.pipelineStage_;
                bitField0_ = (bitField0_ & ~0x00000001);
              } else {
                ensurePipelineStageIsMutable();
                pipelineStage_.addAll(other.pipelineStage_);
              }
              onChanged();
            }
          } else {
            if (!other.pipelineStage_.isEmpty()) {
              if (pipelineStageBuilder_.isEmpty()) {
                pipelineStageBuilder_.dispose();
                pipelineStageBuilder_ = null;
                pipelineStage_ = other.pipelineStage_;
                bitField0_ = (bitField0_ & ~0x00000001);
                pipelineStageBuilder_ = 
                  com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                     getPipelineStageFieldBuilder() : null;
              } else {
                pipelineStageBuilder_.addAllMessages(other.pipelineStage_);
              }
            }
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          for (int i = 0; i < getPipelineStageCount(); i++) {
            if (!getPipelineStage(i).isInitialized()) {
              return false;
            }
          }
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          payment.framework.serializers.Command.CommandProto.PipelineStages parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (payment.framework.serializers.Command.CommandProto.PipelineStages) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.util.List<payment.framework.serializers.Command.CommandProto.Stage> pipelineStage_ =
          java.util.Collections.emptyList();
        private void ensurePipelineStageIsMutable() {
          if (!((bitField0_ & 0x00000001) != 0)) {
            pipelineStage_ = new java.util.ArrayList<payment.framework.serializers.Command.CommandProto.Stage>(pipelineStage_);
            bitField0_ |= 0x00000001;
           }
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
            payment.framework.serializers.Command.CommandProto.Stage, payment.framework.serializers.Command.CommandProto.Stage.Builder, payment.framework.serializers.Command.CommandProto.StageOrBuilder> pipelineStageBuilder_;

        /**
         * <code>repeated .CommandProto.Stage pipelineStage = 1;</code>
         */
        public java.util.List<payment.framework.serializers.Command.CommandProto.Stage> getPipelineStageList() {
          if (pipelineStageBuilder_ == null) {
            return java.util.Collections.unmodifiableList(pipelineStage_);
          } else {
            return pipelineStageBuilder_.getMessageList();
          }
        }
        /**
         * <code>repeated .CommandProto.Stage pipelineStage = 1;</code>
         */
        public int getPipelineStageCount() {
          if (pipelineStageBuilder_ == null) {
            return pipelineStage_.size();
          } else {
            return pipelineStageBuilder_.getCount();
          }
        }
        /**
         * <code>repeated .CommandProto.Stage pipelineStage = 1;</code>
         */
        public payment.framework.serializers.Command.CommandProto.Stage getPipelineStage(int index) {
          if (pipelineStageBuilder_ == null) {
            return pipelineStage_.get(index);
          } else {
            return pipelineStageBuilder_.getMessage(index);
          }
        }
        /**
         * <code>repeated .CommandProto.Stage pipelineStage = 1;</code>
         */
        public Builder setPipelineStage(
            int index, payment.framework.serializers.Command.CommandProto.Stage value) {
          if (pipelineStageBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensurePipelineStageIsMutable();
            pipelineStage_.set(index, value);
            onChanged();
          } else {
            pipelineStageBuilder_.setMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .CommandProto.Stage pipelineStage = 1;</code>
         */
        public Builder setPipelineStage(
            int index, payment.framework.serializers.Command.CommandProto.Stage.Builder builderForValue) {
          if (pipelineStageBuilder_ == null) {
            ensurePipelineStageIsMutable();
            pipelineStage_.set(index, builderForValue.build());
            onChanged();
          } else {
            pipelineStageBuilder_.setMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .CommandProto.Stage pipelineStage = 1;</code>
         */
        public Builder addPipelineStage(payment.framework.serializers.Command.CommandProto.Stage value) {
          if (pipelineStageBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensurePipelineStageIsMutable();
            pipelineStage_.add(value);
            onChanged();
          } else {
            pipelineStageBuilder_.addMessage(value);
          }
          return this;
        }
        /**
         * <code>repeated .CommandProto.Stage pipelineStage = 1;</code>
         */
        public Builder addPipelineStage(
            int index, payment.framework.serializers.Command.CommandProto.Stage value) {
          if (pipelineStageBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensurePipelineStageIsMutable();
            pipelineStage_.add(index, value);
            onChanged();
          } else {
            pipelineStageBuilder_.addMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .CommandProto.Stage pipelineStage = 1;</code>
         */
        public Builder addPipelineStage(
            payment.framework.serializers.Command.CommandProto.Stage.Builder builderForValue) {
          if (pipelineStageBuilder_ == null) {
            ensurePipelineStageIsMutable();
            pipelineStage_.add(builderForValue.build());
            onChanged();
          } else {
            pipelineStageBuilder_.addMessage(builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .CommandProto.Stage pipelineStage = 1;</code>
         */
        public Builder addPipelineStage(
            int index, payment.framework.serializers.Command.CommandProto.Stage.Builder builderForValue) {
          if (pipelineStageBuilder_ == null) {
            ensurePipelineStageIsMutable();
            pipelineStage_.add(index, builderForValue.build());
            onChanged();
          } else {
            pipelineStageBuilder_.addMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .CommandProto.Stage pipelineStage = 1;</code>
         */
        public Builder addAllPipelineStage(
            java.lang.Iterable<? extends payment.framework.serializers.Command.CommandProto.Stage> values) {
          if (pipelineStageBuilder_ == null) {
            ensurePipelineStageIsMutable();
            com.google.protobuf.AbstractMessageLite.Builder.addAll(
                values, pipelineStage_);
            onChanged();
          } else {
            pipelineStageBuilder_.addAllMessages(values);
          }
          return this;
        }
        /**
         * <code>repeated .CommandProto.Stage pipelineStage = 1;</code>
         */
        public Builder clearPipelineStage() {
          if (pipelineStageBuilder_ == null) {
            pipelineStage_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000001);
            onChanged();
          } else {
            pipelineStageBuilder_.clear();
          }
          return this;
        }
        /**
         * <code>repeated .CommandProto.Stage pipelineStage = 1;</code>
         */
        public Builder removePipelineStage(int index) {
          if (pipelineStageBuilder_ == null) {
            ensurePipelineStageIsMutable();
            pipelineStage_.remove(index);
            onChanged();
          } else {
            pipelineStageBuilder_.remove(index);
          }
          return this;
        }
        /**
         * <code>repeated .CommandProto.Stage pipelineStage = 1;</code>
         */
        public payment.framework.serializers.Command.CommandProto.Stage.Builder getPipelineStageBuilder(
            int index) {
          return getPipelineStageFieldBuilder().getBuilder(index);
        }
        /**
         * <code>repeated .CommandProto.Stage pipelineStage = 1;</code>
         */
        public payment.framework.serializers.Command.CommandProto.StageOrBuilder getPipelineStageOrBuilder(
            int index) {
          if (pipelineStageBuilder_ == null) {
            return pipelineStage_.get(index);  } else {
            return pipelineStageBuilder_.getMessageOrBuilder(index);
          }
        }
        /**
         * <code>repeated .CommandProto.Stage pipelineStage = 1;</code>
         */
        public java.util.List<? extends payment.framework.serializers.Command.CommandProto.StageOrBuilder> 
             getPipelineStageOrBuilderList() {
          if (pipelineStageBuilder_ != null) {
            return pipelineStageBuilder_.getMessageOrBuilderList();
          } else {
            return java.util.Collections.unmodifiableList(pipelineStage_);
          }
        }
        /**
         * <code>repeated .CommandProto.Stage pipelineStage = 1;</code>
         */
        public payment.framework.serializers.Command.CommandProto.Stage.Builder addPipelineStageBuilder() {
          return getPipelineStageFieldBuilder().addBuilder(
              payment.framework.serializers.Command.CommandProto.Stage.getDefaultInstance());
        }
        /**
         * <code>repeated .CommandProto.Stage pipelineStage = 1;</code>
         */
        public payment.framework.serializers.Command.CommandProto.Stage.Builder addPipelineStageBuilder(
            int index) {
          return getPipelineStageFieldBuilder().addBuilder(
              index, payment.framework.serializers.Command.CommandProto.Stage.getDefaultInstance());
        }
        /**
         * <code>repeated .CommandProto.Stage pipelineStage = 1;</code>
         */
        public java.util.List<payment.framework.serializers.Command.CommandProto.Stage.Builder> 
             getPipelineStageBuilderList() {
          return getPipelineStageFieldBuilder().getBuilderList();
        }
        private com.google.protobuf.RepeatedFieldBuilderV3<
            payment.framework.serializers.Command.CommandProto.Stage, payment.framework.serializers.Command.CommandProto.Stage.Builder, payment.framework.serializers.Command.CommandProto.StageOrBuilder> 
            getPipelineStageFieldBuilder() {
          if (pipelineStageBuilder_ == null) {
            pipelineStageBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                payment.framework.serializers.Command.CommandProto.Stage, payment.framework.serializers.Command.CommandProto.Stage.Builder, payment.framework.serializers.Command.CommandProto.StageOrBuilder>(
                    pipelineStage_,
                    ((bitField0_ & 0x00000001) != 0),
                    getParentForChildren(),
                    isClean());
            pipelineStage_ = null;
          }
          return pipelineStageBuilder_;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:CommandProto.PipelineStages)
      }

      // @@protoc_insertion_point(class_scope:CommandProto.PipelineStages)
      private static final payment.framework.serializers.Command.CommandProto.PipelineStages DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new payment.framework.serializers.Command.CommandProto.PipelineStages();
      }

      public static payment.framework.serializers.Command.CommandProto.PipelineStages getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<PipelineStages>
          PARSER = new com.google.protobuf.AbstractParser<PipelineStages>() {
        @java.lang.Override
        public PipelineStages parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new PipelineStages(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<PipelineStages> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<PipelineStages> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public payment.framework.serializers.Command.CommandProto.PipelineStages getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int CURRENTSTAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object currentStage_;
    /**
     * <code>required string currentStage = 1;</code>
     * @return Whether the currentStage field is set.
     */
    @java.lang.Override
    public boolean hasCurrentStage() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string currentStage = 1;</code>
     * @return The currentStage.
     */
    @java.lang.Override
    public java.lang.String getCurrentStage() {
      java.lang.Object ref = currentStage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          currentStage_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string currentStage = 1;</code>
     * @return The bytes for currentStage.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCurrentStageBytes() {
      java.lang.Object ref = currentStage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currentStage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROCESSINGPIPELINE_FIELD_NUMBER = 2;
    private payment.framework.serializers.Command.CommandProto.PipelineStages processingPipeline_;
    /**
     * <code>optional .CommandProto.PipelineStages processingPipeline = 2;</code>
     * @return Whether the processingPipeline field is set.
     */
    @java.lang.Override
    public boolean hasProcessingPipeline() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .CommandProto.PipelineStages processingPipeline = 2;</code>
     * @return The processingPipeline.
     */
    @java.lang.Override
    public payment.framework.serializers.Command.CommandProto.PipelineStages getProcessingPipeline() {
      return processingPipeline_ == null ? payment.framework.serializers.Command.CommandProto.PipelineStages.getDefaultInstance() : processingPipeline_;
    }
    /**
     * <code>optional .CommandProto.PipelineStages processingPipeline = 2;</code>
     */
    @java.lang.Override
    public payment.framework.serializers.Command.CommandProto.PipelineStagesOrBuilder getProcessingPipelineOrBuilder() {
      return processingPipeline_ == null ? payment.framework.serializers.Command.CommandProto.PipelineStages.getDefaultInstance() : processingPipeline_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCurrentStage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasProcessingPipeline()) {
        if (!getProcessingPipeline().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, currentStage_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getProcessingPipeline());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, currentStage_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getProcessingPipeline());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof payment.framework.serializers.Command.CommandProto)) {
        return super.equals(obj);
      }
      payment.framework.serializers.Command.CommandProto other = (payment.framework.serializers.Command.CommandProto) obj;

      if (hasCurrentStage() != other.hasCurrentStage()) return false;
      if (hasCurrentStage()) {
        if (!getCurrentStage()
            .equals(other.getCurrentStage())) return false;
      }
      if (hasProcessingPipeline() != other.hasProcessingPipeline()) return false;
      if (hasProcessingPipeline()) {
        if (!getProcessingPipeline()
            .equals(other.getProcessingPipeline())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCurrentStage()) {
        hash = (37 * hash) + CURRENTSTAGE_FIELD_NUMBER;
        hash = (53 * hash) + getCurrentStage().hashCode();
      }
      if (hasProcessingPipeline()) {
        hash = (37 * hash) + PROCESSINGPIPELINE_FIELD_NUMBER;
        hash = (53 * hash) + getProcessingPipeline().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static payment.framework.serializers.Command.CommandProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static payment.framework.serializers.Command.CommandProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static payment.framework.serializers.Command.CommandProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static payment.framework.serializers.Command.CommandProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static payment.framework.serializers.Command.CommandProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static payment.framework.serializers.Command.CommandProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static payment.framework.serializers.Command.CommandProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static payment.framework.serializers.Command.CommandProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static payment.framework.serializers.Command.CommandProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static payment.framework.serializers.Command.CommandProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static payment.framework.serializers.Command.CommandProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static payment.framework.serializers.Command.CommandProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(payment.framework.serializers.Command.CommandProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CommandProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CommandProto)
        payment.framework.serializers.Command.CommandProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return payment.framework.serializers.Command.internal_static_CommandProto_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return payment.framework.serializers.Command.internal_static_CommandProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                payment.framework.serializers.Command.CommandProto.class, payment.framework.serializers.Command.CommandProto.Builder.class);
      }

      // Construct using payment.framework.serializers.Command.CommandProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getProcessingPipelineFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        currentStage_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (processingPipelineBuilder_ == null) {
          processingPipeline_ = null;
        } else {
          processingPipelineBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return payment.framework.serializers.Command.internal_static_CommandProto_descriptor;
      }

      @java.lang.Override
      public payment.framework.serializers.Command.CommandProto getDefaultInstanceForType() {
        return payment.framework.serializers.Command.CommandProto.getDefaultInstance();
      }

      @java.lang.Override
      public payment.framework.serializers.Command.CommandProto build() {
        payment.framework.serializers.Command.CommandProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public payment.framework.serializers.Command.CommandProto buildPartial() {
        payment.framework.serializers.Command.CommandProto result = new payment.framework.serializers.Command.CommandProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.currentStage_ = currentStage_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          if (processingPipelineBuilder_ == null) {
            result.processingPipeline_ = processingPipeline_;
          } else {
            result.processingPipeline_ = processingPipelineBuilder_.build();
          }
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof payment.framework.serializers.Command.CommandProto) {
          return mergeFrom((payment.framework.serializers.Command.CommandProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(payment.framework.serializers.Command.CommandProto other) {
        if (other == payment.framework.serializers.Command.CommandProto.getDefaultInstance()) return this;
        if (other.hasCurrentStage()) {
          bitField0_ |= 0x00000001;
          currentStage_ = other.currentStage_;
          onChanged();
        }
        if (other.hasProcessingPipeline()) {
          mergeProcessingPipeline(other.getProcessingPipeline());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasCurrentStage()) {
          return false;
        }
        if (hasProcessingPipeline()) {
          if (!getProcessingPipeline().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        payment.framework.serializers.Command.CommandProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (payment.framework.serializers.Command.CommandProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object currentStage_ = "";
      /**
       * <code>required string currentStage = 1;</code>
       * @return Whether the currentStage field is set.
       */
      public boolean hasCurrentStage() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string currentStage = 1;</code>
       * @return The currentStage.
       */
      public java.lang.String getCurrentStage() {
        java.lang.Object ref = currentStage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            currentStage_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string currentStage = 1;</code>
       * @return The bytes for currentStage.
       */
      public com.google.protobuf.ByteString
          getCurrentStageBytes() {
        java.lang.Object ref = currentStage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currentStage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string currentStage = 1;</code>
       * @param value The currentStage to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentStage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        currentStage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string currentStage = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrentStage() {
        bitField0_ = (bitField0_ & ~0x00000001);
        currentStage_ = getDefaultInstance().getCurrentStage();
        onChanged();
        return this;
      }
      /**
       * <code>required string currentStage = 1;</code>
       * @param value The bytes for currentStage to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentStageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        currentStage_ = value;
        onChanged();
        return this;
      }

      private payment.framework.serializers.Command.CommandProto.PipelineStages processingPipeline_;
      private com.google.protobuf.SingleFieldBuilderV3<
          payment.framework.serializers.Command.CommandProto.PipelineStages, payment.framework.serializers.Command.CommandProto.PipelineStages.Builder, payment.framework.serializers.Command.CommandProto.PipelineStagesOrBuilder> processingPipelineBuilder_;
      /**
       * <code>optional .CommandProto.PipelineStages processingPipeline = 2;</code>
       * @return Whether the processingPipeline field is set.
       */
      public boolean hasProcessingPipeline() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional .CommandProto.PipelineStages processingPipeline = 2;</code>
       * @return The processingPipeline.
       */
      public payment.framework.serializers.Command.CommandProto.PipelineStages getProcessingPipeline() {
        if (processingPipelineBuilder_ == null) {
          return processingPipeline_ == null ? payment.framework.serializers.Command.CommandProto.PipelineStages.getDefaultInstance() : processingPipeline_;
        } else {
          return processingPipelineBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .CommandProto.PipelineStages processingPipeline = 2;</code>
       */
      public Builder setProcessingPipeline(payment.framework.serializers.Command.CommandProto.PipelineStages value) {
        if (processingPipelineBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          processingPipeline_ = value;
          onChanged();
        } else {
          processingPipelineBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .CommandProto.PipelineStages processingPipeline = 2;</code>
       */
      public Builder setProcessingPipeline(
          payment.framework.serializers.Command.CommandProto.PipelineStages.Builder builderForValue) {
        if (processingPipelineBuilder_ == null) {
          processingPipeline_ = builderForValue.build();
          onChanged();
        } else {
          processingPipelineBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .CommandProto.PipelineStages processingPipeline = 2;</code>
       */
      public Builder mergeProcessingPipeline(payment.framework.serializers.Command.CommandProto.PipelineStages value) {
        if (processingPipelineBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
              processingPipeline_ != null &&
              processingPipeline_ != payment.framework.serializers.Command.CommandProto.PipelineStages.getDefaultInstance()) {
            processingPipeline_ =
              payment.framework.serializers.Command.CommandProto.PipelineStages.newBuilder(processingPipeline_).mergeFrom(value).buildPartial();
          } else {
            processingPipeline_ = value;
          }
          onChanged();
        } else {
          processingPipelineBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .CommandProto.PipelineStages processingPipeline = 2;</code>
       */
      public Builder clearProcessingPipeline() {
        if (processingPipelineBuilder_ == null) {
          processingPipeline_ = null;
          onChanged();
        } else {
          processingPipelineBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .CommandProto.PipelineStages processingPipeline = 2;</code>
       */
      public payment.framework.serializers.Command.CommandProto.PipelineStages.Builder getProcessingPipelineBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getProcessingPipelineFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .CommandProto.PipelineStages processingPipeline = 2;</code>
       */
      public payment.framework.serializers.Command.CommandProto.PipelineStagesOrBuilder getProcessingPipelineOrBuilder() {
        if (processingPipelineBuilder_ != null) {
          return processingPipelineBuilder_.getMessageOrBuilder();
        } else {
          return processingPipeline_ == null ?
              payment.framework.serializers.Command.CommandProto.PipelineStages.getDefaultInstance() : processingPipeline_;
        }
      }
      /**
       * <code>optional .CommandProto.PipelineStages processingPipeline = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          payment.framework.serializers.Command.CommandProto.PipelineStages, payment.framework.serializers.Command.CommandProto.PipelineStages.Builder, payment.framework.serializers.Command.CommandProto.PipelineStagesOrBuilder> 
          getProcessingPipelineFieldBuilder() {
        if (processingPipelineBuilder_ == null) {
          processingPipelineBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              payment.framework.serializers.Command.CommandProto.PipelineStages, payment.framework.serializers.Command.CommandProto.PipelineStages.Builder, payment.framework.serializers.Command.CommandProto.PipelineStagesOrBuilder>(
                  getProcessingPipeline(),
                  getParentForChildren(),
                  isClean());
          processingPipeline_ = null;
        }
        return processingPipelineBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CommandProto)
    }

    // @@protoc_insertion_point(class_scope:CommandProto)
    private static final payment.framework.serializers.Command.CommandProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new payment.framework.serializers.Command.CommandProto();
    }

    public static payment.framework.serializers.Command.CommandProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CommandProto>
        PARSER = new com.google.protobuf.AbstractParser<CommandProto>() {
      @java.lang.Override
      public CommandProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CommandProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CommandProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CommandProto> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public payment.framework.serializers.Command.CommandProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommandProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommandProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommandProto_Stage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommandProto_Stage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommandProto_PipelineStages_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommandProto_PipelineStages_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030main/proto/command.proto\"\304\001\n\014CommandPr" +
      "oto\022\024\n\014currentStage\030\001 \002(\t\0228\n\022processingP" +
      "ipeline\030\002 \001(\0132\034.CommandProto.PipelineSta" +
      "ges\032&\n\005Stage\022\r\n\005stage\030\001 \002(\t\022\016\n\006status\030\002 " +
      "\002(\010\032<\n\016PipelineStages\022*\n\rpipelineStage\030\001" +
      " \003(\0132\023.CommandProto.StageB\037\n\035payment.fra" +
      "mework.serializers"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CommandProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CommandProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommandProto_descriptor,
        new java.lang.String[] { "CurrentStage", "ProcessingPipeline", });
    internal_static_CommandProto_Stage_descriptor =
      internal_static_CommandProto_descriptor.getNestedTypes().get(0);
    internal_static_CommandProto_Stage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommandProto_Stage_descriptor,
        new java.lang.String[] { "Stage", "Status", });
    internal_static_CommandProto_PipelineStages_descriptor =
      internal_static_CommandProto_descriptor.getNestedTypes().get(1);
    internal_static_CommandProto_PipelineStages_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommandProto_PipelineStages_descriptor,
        new java.lang.String[] { "PipelineStage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
